Table Users{
  id int pk
  name vatchar(255) [not null]
  email varchar(255) [not null]
  country int
  mobile varchar(15)
}

Table Countries{
  code int pk
  name varchar(255) [not null]
}

Table Books{
  id int pk 
  title varchar(255) [not null]
  isbn varchar(10)
}

Table TitleAuthors{
  id int pk
  book int
  author int
}

Table Inventory{
  id int pk
  book int
  owner int
  status varchar(10)
  possessor int
}

Table Authors{
  id int pk
  name varchar(255)
}

Ref: "Users"."country" > "Countries"."code"

Ref: "Books"."id" < "TitleAuthors"."book"

Ref: "Authors"."id" < "TitleAuthors"."author"

Ref: "Users"."name" < "Inventory"."owner"

Ref: "Users"."name" < "Inventory"."possessor"

Ref: "Books"."id" < "Inventory"."book"